
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerCollision : MonoBehaviour
{
   
    private void OnCollisionEnter(Collision other)
    {
        
        if(other.gameObject.CompareTag("Portal"))
        {
            Debug.Log ("Entrando en colisi贸n con un Shrinker");
        }
        else 
        {
            Debug.Log("Entrando en colisi贸n con -> " + other.gameObject.name);
        }

    }

    private void OnCollisionExit(Collision other)
    {
        Debug.Log("Saliendo de colisi贸n con -> " + other.gameObject.name);
    }

    private void OnCollisionStay(Collision other)
    {
        Debug.Log("En colisi贸n con -> " + other.gameObject.name);
    }

    private void OnTriggerEnter(Collider other)
    {
        Debug.Log("Entrando en -> " + other.gameObject.name);


    }

    private void OnTriggerExit(Collider other)
    {
        Debug.Log("Saliendo de -> " + other.gameObject.name);
    }

    private void OnTriggerStay(Collider other)
    {
        Debug.Log("Dentro de -> " + other.gameObject.name);
    }
}
